### PR TITLE
James

### PR DESCRIPTION
**Pull request by jameswniu**
Please look through README.md and add your area of interest under "Plausible Topics of Interest:" in the square brackets [x]

A suitable format can be "Impact of masks mandates on X - question?" as written under James.

### CODE REVIEW

**Comment by Ekaufman555** [comment]
Impact of mask mandates on Covid hotspots and outbreaks

Comparison of timing of mask mandates whether policy was proactive or reactive.

Correlation of mask mandates and vaccination rates for a given area. Are mask mandates predictive of vaccination status.

**Review by Ekaufman555 — APPROVED** [review]
Impact of mask mandates on Covid hotspots and outbreaks

Comparison of timing of mask mandates whether policy was proactive or reactive. in regards to outbreaks and hotspots

Correlation of mask mandates and vaccination rates for a given area. Are mask mandates predictive of vaccination status.

**Review by Steven-Broyles — APPROVED** [review]
Looks good! Sorry I've been busy these few days

**Comment by EHVargas22** [comment]
Looks good!

**Pull request merged**
